# Site wide configuration

title: "www.abgraphy.com"
description: ".. in making photographs alive"
#if you modify locale please have a look at _data/messages.yml too
locale: en
#for meta name="author" :
author: aoplus

#Target date in UTC / GMT
countdown:
  theme: blue
  year: 2017
  month: 3
  day: 31
  hour: 0
  minute: 0

# Site owner
owner: 
  name: anush bulusu
  email: anush.bulusu@gmail.com
  twitter:
  google-plus:
  instagramm: anushbulusu
  facebook: abgraphy
  aboutlink:
    url: www.facebook.com/anushbulusu
    caption: 


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
