# Site settings
# in the templates available like {{ site.myvariable }}.
title: Welcome to abgraphy. I freeze time for you.
email: anush@abgraphy.com
brand: AB Graphy
headline: I freeze time.
description: > # this means to ignore newlines until "baseurl:"
 New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.abgraphy.com" # the base hostname & protocol for your site
copyright: 2017 AB Graphy, All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 325047

# Contacts
email: anushbulusu@abgraphy.com
phone: +91 88840 00292

# Tracking
googleAnalitycsID: UA-91023860-1

